server:
  port: 8080
  error:
    include-stacktrace: always
    
spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: change_me
            client-secret: change_me
          google:
            client-id: change_me
            client-secret: change_me         
  data:
    cassandra:
      schema-action: create-if-not-exists

astra:
  api:
    application-token: ${ASTRA_ORG_TOKEN}
    database-id: ${ASTRA_DB_ID}
    database-region: ${ASTRA_DB_REGION}
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE}
      advanced:
        connection:
          init-query-timeout: 10s