server:
  port: 8080
  error:
    include-stacktrace: always
    
spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a02bb4dbf526cbd2bde1
            client-secret: 6177e2f17443710a7a87cc98d6e2bb1de831facb
          google:
            client-id: 222261517939-30bksvlbjccqnthh3ofrqqhgebum7bre.apps.googleusercontent.com
            client-secret: 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
  data:
    cassandra:
      schema-action: create-if-not-exists

astra:
  api:
    application-token: ${ASTRA_ORG_TOKEN}
    database-id: ${ASTRA_DB_ID}
    database-region: ${ASTRA_DB_REGION}
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE}
      advanced:
        connection:
          init-query-timeout: 10s